### ISSUE TITLE
New icon (similar to my proposal for FADCAM)

### ISSUE THREAD

**Issue by sonalder-darlene** [anonfaded/FadCrypt#1]
Here are two quickly made icon to make an icon similar to the one I proposed for FADCAM I've made both a transparent PNG and a icon in a squircle since Windows app usually don't follow an icon shape as it is on smartphone.

![FADCRYPT_icon](https://github.com/user-attachments/assets/87f78e99-2f99-45ae-83ce-c39df22c7957)
![FADCRYPT_icon_Squircle](https://github.com/user-attachments/assets/07a0c239-df50-4830-b64c-1f45207e8c89)

**Comment by anonfaded** [comment]
Nice, you can open a Pull Request and submit the icons. Will use this icon as 'system tray' as the app mostly stays there.
And will tag you in the Credits section in the README soon.
